# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.reactors_inner_reactor_skill_power_inner_enchant_effect_inner import ReactorsInnerReactorSkillPowerInnerEnchantEffectInner

class TestReactorsInnerReactorSkillPowerInnerEnchantEffectInner(unittest.TestCase):
    """ReactorsInnerReactorSkillPowerInnerEnchantEffectInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReactorsInnerReactorSkillPowerInnerEnchantEffectInner:
        """Test ReactorsInnerReactorSkillPowerInnerEnchantEffectInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReactorsInnerReactorSkillPowerInnerEnchantEffectInner`
        """
        model = ReactorsInnerReactorSkillPowerInnerEnchantEffectInner()
        if include_optional:
            return ReactorsInnerReactorSkillPowerInnerEnchantEffectInner(
                enchant_level = 1.337,
                stat_id = '',
                value = 1.337
            )
        else:
            return ReactorsInnerReactorSkillPowerInnerEnchantEffectInner(
        )
        """

    def testReactorsInnerReactorSkillPowerInnerEnchantEffectInner(self):
        """Test ReactorsInnerReactorSkillPowerInnerEnchantEffectInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
