# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.titles_inner import TitlesInner

class TestTitlesInner(unittest.TestCase):
    """TitlesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TitlesInner:
        """Test TitlesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TitlesInner`
        """
        model = TitlesInner()
        if include_optional:
            return TitlesInner(
                title_id = '',
                title_name = ''
            )
        else:
            return TitlesInner(
        )
        """

    def testTitlesInner(self):
        """Test TitlesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
