# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.module_recommendation_response_descendant_recommendation_inner import ModuleRecommendationResponseDescendantRecommendationInner

class TestModuleRecommendationResponseDescendantRecommendationInner(unittest.TestCase):
    """ModuleRecommendationResponseDescendantRecommendationInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModuleRecommendationResponseDescendantRecommendationInner:
        """Test ModuleRecommendationResponseDescendantRecommendationInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModuleRecommendationResponseDescendantRecommendationInner`
        """
        model = ModuleRecommendationResponseDescendantRecommendationInner()
        if include_optional:
            return ModuleRecommendationResponseDescendantRecommendationInner(
                module_id = ''
            )
        else:
            return ModuleRecommendationResponseDescendantRecommendationInner(
        )
        """

    def testModuleRecommendationResponseDescendantRecommendationInner(self):
        """Test ModuleRecommendationResponseDescendantRecommendationInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
