# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.core_types_inner_core_option_inner_available_item_option_inner import CoreTypesInnerCoreOptionInnerAvailableItemOptionInner

class TestCoreTypesInnerCoreOptionInnerAvailableItemOptionInner(unittest.TestCase):
    """CoreTypesInnerCoreOptionInnerAvailableItemOptionInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoreTypesInnerCoreOptionInnerAvailableItemOptionInner:
        """Test CoreTypesInnerCoreOptionInnerAvailableItemOptionInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoreTypesInnerCoreOptionInnerAvailableItemOptionInner`
        """
        model = CoreTypesInnerCoreOptionInnerAvailableItemOptionInner()
        if include_optional:
            return CoreTypesInnerCoreOptionInnerAvailableItemOptionInner(
                item_option = '',
                option_type = '',
                option_grade = '',
                option_effect = tfd_api_client.models.core_types_inner_core_option_inner_available_item_option_inner_option_effect.CoreTypes_inner_core_option_inner_available_item_option_inner_option_effect(
                    stat_id = '', 
                    operator_type = '', 
                    min_stat_value = 1.337, 
                    max_stat_value = 1.337, ),
                rate = 1.337
            )
        else:
            return CoreTypesInnerCoreOptionInnerAvailableItemOptionInner(
        )
        """

    def testCoreTypesInnerCoreOptionInnerAvailableItemOptionInner(self):
        """Test CoreTypesInnerCoreOptionInnerAvailableItemOptionInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
