# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.user_reactor import UserReactor

class TestUserReactor(unittest.TestCase):
    """UserReactor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserReactor:
        """Test UserReactor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserReactor`
        """
        model = UserReactor()
        if include_optional:
            return UserReactor(
                ouid = '',
                user_name = 'Nickname#1234',
                reactor_id = '',
                reactor_slot_id = '',
                reactor_level = 1.337,
                reactor_additional_stat = [
                    tfd_api_client.models.user_reactor_reactor_additional_stat_inner.UserReactor_reactor_additional_stat_inner(
                        additional_stat_name = '', 
                        additional_stat_value = '', )
                    ],
                reactor_enchant_level = 1.337
            )
        else:
            return UserReactor(
        )
        """

    def testUserReactor(self):
        """Test UserReactor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
