# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.modules_inner import ModulesInner

class TestModulesInner(unittest.TestCase):
    """ModulesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModulesInner:
        """Test ModulesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModulesInner`
        """
        model = ModulesInner()
        if include_optional:
            return ModulesInner(
                module_name = '',
                module_id = '',
                image_url = '',
                module_type = '',
                module_tier_id = '',
                module_socket_type = '',
                module_class = '',
                available_weapon_type = [
                    ''
                    ],
                available_descendant_id = [
                    ''
                    ],
                available_module_slot_type = [
                    ''
                    ],
                module_stat = [
                    tfd_api_client.models.modules_inner_module_stat_inner.Modules_inner_module_stat_inner(
                        level = 1.337, 
                        module_capacity = 1.337, 
                        value = '', )
                    ]
            )
        else:
            return ModulesInner(
        )
        """

    def testModulesInner(self):
        """Test ModulesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
