# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.reactors_inner_reactor_skill_power_inner_skill_power_coefficient_inner import ReactorsInnerReactorSkillPowerInnerSkillPowerCoefficientInner

class TestReactorsInnerReactorSkillPowerInnerSkillPowerCoefficientInner(unittest.TestCase):
    """ReactorsInnerReactorSkillPowerInnerSkillPowerCoefficientInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReactorsInnerReactorSkillPowerInnerSkillPowerCoefficientInner:
        """Test ReactorsInnerReactorSkillPowerInnerSkillPowerCoefficientInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReactorsInnerReactorSkillPowerInnerSkillPowerCoefficientInner`
        """
        model = ReactorsInnerReactorSkillPowerInnerSkillPowerCoefficientInner()
        if include_optional:
            return ReactorsInnerReactorSkillPowerInnerSkillPowerCoefficientInner(
                coefficient_stat_id = '',
                coefficient_stat_value = 1.337
            )
        else:
            return ReactorsInnerReactorSkillPowerInnerSkillPowerCoefficientInner(
        )
        """

    def testReactorsInnerReactorSkillPowerInnerSkillPowerCoefficientInner(self):
        """Test ReactorsInnerReactorSkillPowerInnerSkillPowerCoefficientInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
