# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.research_inner import ResearchInner

class TestResearchInner(unittest.TestCase):
    """ResearchInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResearchInner:
        """Test ResearchInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResearchInner`
        """
        model = ResearchInner()
        if include_optional:
            return ResearchInner(
                research_id = '',
                research_name = '',
                repeatable_research = True,
                research_type = '',
                research_time = 1.337,
                research_cost = [
                    tfd_api_client.models.research_inner_research_cost_inner.Research_inner_research_cost_inner(
                        currency_type = '', 
                        currency_value = 1.337, )
                    ],
                research_boost_cost = [
                    tfd_api_client.models.research_inner_research_cost_inner.Research_inner_research_cost_inner(
                        currency_type = '', 
                        currency_value = 1.337, )
                    ],
                research_result = [
                    tfd_api_client.models.research_inner_research_result_inner.Research_inner_research_result_inner(
                        meta_type = '', 
                        meta_id = '', 
                        result_count = 1.337, )
                    ],
                research_material = [
                    tfd_api_client.models.research_inner_research_material_inner.Research_inner_research_material_inner(
                        meta_type = '', 
                        meta_id = '', 
                        material_count = 1.337, 
                        research_id = [
                            ''
                            ], )
                    ]
            )
        else:
            return ResearchInner(
        )
        """

    def testResearchInner(self):
        """Test ResearchInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
