# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.research_inner_research_material_inner import ResearchInnerResearchMaterialInner

class TestResearchInnerResearchMaterialInner(unittest.TestCase):
    """ResearchInnerResearchMaterialInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResearchInnerResearchMaterialInner:
        """Test ResearchInnerResearchMaterialInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResearchInnerResearchMaterialInner`
        """
        model = ResearchInnerResearchMaterialInner()
        if include_optional:
            return ResearchInnerResearchMaterialInner(
                meta_type = '',
                meta_id = '',
                material_count = 1.337,
                research_id = [
                    ''
                    ]
            )
        else:
            return ResearchInnerResearchMaterialInner(
        )
        """

    def testResearchInnerResearchMaterialInner(self):
        """Test ResearchInnerResearchMaterialInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
