# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_thefirstdescendant_get_user_arche_tuning(self) -> None:
        """Test case for thefirstdescendant_get_user_arche_tuning

        Retrieve Arche tuning information
        """
        pass

    def test_thefirstdescendant_get_user_basic(self) -> None:
        """Test case for thefirstdescendant_get_user_basic

        Retrieve basic information
        """
        pass

    def test_thefirstdescendant_get_user_descendant(self) -> None:
        """Test case for thefirstdescendant_get_user_descendant

        Retrieve equipped descendant information
        """
        pass

    def test_thefirstdescendant_get_user_external_component(self) -> None:
        """Test case for thefirstdescendant_get_user_external_component

        Retrieve equipped external component information
        """
        pass

    def test_thefirstdescendant_get_user_id(self) -> None:
        """Test case for thefirstdescendant_get_user_id

        Retrieve account identifier (OUID)
        """
        pass

    def test_thefirstdescendant_get_user_reactor(self) -> None:
        """Test case for thefirstdescendant_get_user_reactor

        Retrieve equipped Reactor information
        """
        pass

    def test_thefirstdescendant_get_user_weapon(self) -> None:
        """Test case for thefirstdescendant_get_user_weapon

        Retrieve equipped weapon information
        """
        pass


if __name__ == '__main__':
    unittest.main()
