# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.reactors_inner_reactor_skill_power_inner import ReactorsInnerReactorSkillPowerInner

class TestReactorsInnerReactorSkillPowerInner(unittest.TestCase):
    """ReactorsInnerReactorSkillPowerInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReactorsInnerReactorSkillPowerInner:
        """Test ReactorsInnerReactorSkillPowerInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReactorsInnerReactorSkillPowerInner`
        """
        model = ReactorsInnerReactorSkillPowerInner()
        if include_optional:
            return ReactorsInnerReactorSkillPowerInner(
                level = 1.337,
                skill_atk_power = 1.337,
                sub_skill_atk_power = 1.337,
                skill_power_coefficient = [
                    tfd_api_client.models.reactors_inner_reactor_skill_power_inner_skill_power_coefficient_inner.Reactors_inner_reactor_skill_power_inner_skill_power_coefficient_inner(
                        coefficient_stat_id = '', 
                        coefficient_stat_value = 1.337, )
                    ],
                enchant_effect = [
                    tfd_api_client.models.reactors_inner_reactor_skill_power_inner_enchant_effect_inner.Reactors_inner_reactor_skill_power_inner_enchant_effect_inner(
                        enchant_level = 1.337, 
                        stat_id = '', 
                        value = 1.337, )
                    ]
            )
        else:
            return ReactorsInnerReactorSkillPowerInner(
        )
        """

    def testReactorsInnerReactorSkillPowerInner(self):
        """Test ReactorsInnerReactorSkillPowerInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
