# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.modules_inner_module_stat_inner import ModulesInnerModuleStatInner

class TestModulesInnerModuleStatInner(unittest.TestCase):
    """ModulesInnerModuleStatInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModulesInnerModuleStatInner:
        """Test ModulesInnerModuleStatInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModulesInnerModuleStatInner`
        """
        model = ModulesInnerModuleStatInner()
        if include_optional:
            return ModulesInnerModuleStatInner(
                level = 1.337,
                module_capacity = 1.337,
                value = ''
            )
        else:
            return ModulesInnerModuleStatInner(
        )
        """

    def testModulesInnerModuleStatInner(self):
        """Test ModulesInnerModuleStatInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
