# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.user_descendant_customizing_inner import UserDescendantCustomizingInner

class TestUserDescendantCustomizingInner(unittest.TestCase):
    """UserDescendantCustomizingInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserDescendantCustomizingInner:
        """Test UserDescendantCustomizingInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserDescendantCustomizingInner`
        """
        model = UserDescendantCustomizingInner()
        if include_optional:
            return UserDescendantCustomizingInner(
                customizing_item_slot_id = '',
                customizing_item_type = '',
                customizing_item_id = '',
                customizing_item_evolution_stage = 1.337,
                customizing_item_current_evolution_stage = 1.337,
                paint = [
                    tfd_api_client.models.user_descendant_customizing_inner_paint_inner.UserDescendant_customizing_inner_paint_inner(
                        customizing_item_slot_id = '', 
                        customizing_item_type = '', 
                        customizing_item_id = '', )
                    ]
            )
        else:
            return UserDescendantCustomizingInner(
        )
        """

    def testUserDescendantCustomizingInner(self):
        """Test UserDescendantCustomizingInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
