# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.module_recommendations import ModuleRecommendations

class TestModuleRecommendations(unittest.TestCase):
    """ModuleRecommendations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModuleRecommendations:
        """Test ModuleRecommendations
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModuleRecommendations`
        """
        model = ModuleRecommendations()
        if include_optional:
            return ModuleRecommendations(
                descendant = tfd_api_client.models.module_recommendations_descendant.ModuleRecommendations_descendant(
                    descendant_id = '', 
                    recommendation = [
                        tfd_api_client.models.module_recommendations_descendant_recommendation_inner.ModuleRecommendations_descendant_recommendation_inner(
                            module_id = '', )
                        ], ),
                weapon = tfd_api_client.models.module_recommendations_weapon.ModuleRecommendations_weapon(
                    weapon_id = '', 
                    recommendation = [
                        tfd_api_client.models.module_recommendations_descendant_recommendation_inner.ModuleRecommendations_descendant_recommendation_inner(
                            module_id = '', )
                        ], )
            )
        else:
            return ModuleRecommendations(
        )
        """

    def testModuleRecommendations(self):
        """Test ModuleRecommendations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
