# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.user_descendant_module_inner import UserDescendantModuleInner

class TestUserDescendantModuleInner(unittest.TestCase):
    """UserDescendantModuleInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserDescendantModuleInner:
        """Test UserDescendantModuleInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserDescendantModuleInner`
        """
        model = UserDescendantModuleInner()
        if include_optional:
            return UserDescendantModuleInner(
                module_slot_id = '',
                module_id = '',
                module_enchant_level = 1.337
            )
        else:
            return UserDescendantModuleInner(
        )
        """

    def testUserDescendantModuleInner(self):
        """Test UserDescendantModuleInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
