# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.weapons_inner_firearm_atk_inner import WeaponsInnerFirearmAtkInner

class TestWeaponsInnerFirearmAtkInner(unittest.TestCase):
    """WeaponsInnerFirearmAtkInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WeaponsInnerFirearmAtkInner:
        """Test WeaponsInnerFirearmAtkInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WeaponsInnerFirearmAtkInner`
        """
        model = WeaponsInnerFirearmAtkInner()
        if include_optional:
            return WeaponsInnerFirearmAtkInner(
                level = 1.337,
                firearm = [
                    tfd_api_client.models.weapons_inner_firearm_atk_inner_firearm_inner.Weapons_inner_firearm_atk_inner_firearm_inner(
                        firearm_atk_type = '', 
                        firearm_atk_value = 1.337, )
                    ]
            )
        else:
            return WeaponsInnerFirearmAtkInner(
        )
        """

    def testWeaponsInnerFirearmAtkInner(self):
        """Test WeaponsInnerFirearmAtkInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
