# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.user_weapon_weapon_inner_weapon_additional_stat_inner import UserWeaponWeaponInnerWeaponAdditionalStatInner

class TestUserWeaponWeaponInnerWeaponAdditionalStatInner(unittest.TestCase):
    """UserWeaponWeaponInnerWeaponAdditionalStatInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserWeaponWeaponInnerWeaponAdditionalStatInner:
        """Test UserWeaponWeaponInnerWeaponAdditionalStatInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserWeaponWeaponInnerWeaponAdditionalStatInner`
        """
        model = UserWeaponWeaponInnerWeaponAdditionalStatInner()
        if include_optional:
            return UserWeaponWeaponInnerWeaponAdditionalStatInner(
                additional_stat_name = '',
                additional_stat_value = ''
            )
        else:
            return UserWeaponWeaponInnerWeaponAdditionalStatInner(
        )
        """

    def testUserWeaponWeaponInnerWeaponAdditionalStatInner(self):
        """Test UserWeaponWeaponInnerWeaponAdditionalStatInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
