# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.user_basic import UserBasic

class TestUserBasic(unittest.TestCase):
    """UserBasic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserBasic:
        """Test UserBasic
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserBasic`
        """
        model = UserBasic()
        if include_optional:
            return UserBasic(
                ouid = '',
                user_name = 'Nickname#1234',
                platform_type = '',
                mastery_rank_level = 1.337,
                mastery_rank_exp = 1.337,
                title_prefix_id = '',
                title_suffix_id = '',
                os_language = '',
                game_language = '',
                medal_id = '',
                medal_level = 1.337
            )
        else:
            return UserBasic(
        )
        """

    def testUserBasic(self):
        """Test UserBasic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
