# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.external_components_inner import ExternalComponentsInner

class TestExternalComponentsInner(unittest.TestCase):
    """ExternalComponentsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalComponentsInner:
        """Test ExternalComponentsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalComponentsInner`
        """
        model = ExternalComponentsInner()
        if include_optional:
            return ExternalComponentsInner(
                external_component_id = '',
                external_component_name = '',
                image_url = '',
                external_component_equipment_type = '',
                external_component_tier_id = '',
                available_core_slot = '',
                base_stat = [
                    tfd_api_client.models.external_components_inner_base_stat_inner.ExternalComponents_inner_base_stat_inner(
                        level = 1.337, 
                        stat_id = '', 
                        stat_value = 1.337, )
                    ],
                set_option_detail = [
                    tfd_api_client.models.external_components_inner_set_option_detail_inner.ExternalComponents_inner_set_option_detail_inner(
                        set_option = '', 
                        set_count = 1.337, 
                        set_option_effect = '', )
                    ]
            )
        else:
            return ExternalComponentsInner(
        )
        """

    def testExternalComponentsInner(self):
        """Test ExternalComponentsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
