# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.user_descendant import UserDescendant

class TestUserDescendant(unittest.TestCase):
    """UserDescendant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserDescendant:
        """Test UserDescendant
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserDescendant`
        """
        model = UserDescendant()
        if include_optional:
            return UserDescendant(
                ouid = '',
                user_name = 'Nickname#1234',
                descendant_id = '',
                descendant_slot_id = '',
                descendant_level = 1.337,
                module_max_capacity = 1.337,
                module_capacity = 1.337,
                energy_activator_use_count = 1.337,
                module = [
                    tfd_api_client.models.user_descendant_module_inner.UserDescendant_module_inner(
                        module_slot_id = '', 
                        module_id = '', 
                        module_enchant_level = 1.337, )
                    ],
                customizing = [
                    tfd_api_client.models.user_descendant_customizing_inner.UserDescendant_customizing_inner(
                        customizing_item_slot_id = '', 
                        customizing_item_type = '', 
                        customizing_item_id = '', 
                        customizing_item_evolution_stage = 1.337, 
                        customizing_item_current_evolution_stage = 1.337, 
                        paint = [
                            tfd_api_client.models.user_descendant_customizing_inner_paint_inner.UserDescendant_customizing_inner_paint_inner(
                                customizing_item_slot_id = '', 
                                customizing_item_type = '', 
                                customizing_item_id = '', )
                            ], )
                    ]
            )
        else:
            return UserDescendant(
        )
        """

    def testUserDescendant(self):
        """Test UserDescendant"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
