# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.amorphous_open_condition_descriptions_inner import AmorphousOpenConditionDescriptionsInner

class TestAmorphousOpenConditionDescriptionsInner(unittest.TestCase):
    """AmorphousOpenConditionDescriptionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AmorphousOpenConditionDescriptionsInner:
        """Test AmorphousOpenConditionDescriptionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AmorphousOpenConditionDescriptionsInner`
        """
        model = AmorphousOpenConditionDescriptionsInner()
        if include_optional:
            return AmorphousOpenConditionDescriptionsInner(
                amorphous_open_condition_id = '',
                amorphous_open_condition_name = ''
            )
        else:
            return AmorphousOpenConditionDescriptionsInner(
        )
        """

    def testAmorphousOpenConditionDescriptionsInner(self):
        """Test AmorphousOpenConditionDescriptionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
