# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tfd_api_client.models.arche_tuning_boards_inner import ArcheTuningBoardsInner

class TestArcheTuningBoardsInner(unittest.TestCase):
    """ArcheTuningBoardsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArcheTuningBoardsInner:
        """Test ArcheTuningBoardsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArcheTuningBoardsInner`
        """
        model = ArcheTuningBoardsInner()
        if include_optional:
            return ArcheTuningBoardsInner(
                arche_tuning_board_id = '',
                row_size = 1.337,
                column_size = 1.337,
                node = [
                    tfd_api_client.models.arche_tuning_boards_inner_node_inner.ArcheTuningBoards_inner_node_inner(
                        node_id = '', 
                        position_row = 1.337, 
                        position_column = 1.337, )
                    ]
            )
        else:
            return ArcheTuningBoardsInner(
        )
        """

    def testArcheTuningBoardsInner(self):
        """Test ArcheTuningBoardsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
