# openapi-codegen.conf.yaml
generatorName: python
inputSpec: ./spec/tfd.openapi.yaml  # Path to your OpenAPI spec file
outputDir: ./out/python-client

# Optional: Additional configuration options
additionalProperties:
  packageName: tfd_api_client
  projectName: TFD API Client
  # packageVersion: 1.0.0
  hideGenerationTimestamp: true

# Optional: Specify which files to generate
# globalProperties:
#   models: ""
#   apis: ""

# Optional: Specify which models or APIs to include/exclude
# models:
#   - Pet
#   - User
# apis:
#   - PetApi
#   - UserApi