# coding: utf-8

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from tfd_api_client.models.user_descendant_customizing_inner_paint_inner import UserDescendantCustomizingInnerPaintInner
from typing import Optional, Set
from typing_extensions import Self

class UserDescendantCustomizingInner(BaseModel):
    """
    UserDescendantCustomizingInner
    """ # noqa: E501
    customizing_item_slot_id: Optional[StrictStr] = Field(default=None, description="Customization item slot identifier")
    customizing_item_type: Optional[StrictStr] = Field(default=None, description="Customization item type")
    customizing_item_id: Optional[StrictStr] = Field(default=None, description="Customization item identifier (Refer to /meta/customizing-item API)")
    customizing_item_evolution_stage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Evolution stage of the customization item")
    customizing_item_current_evolution_stage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Currently selected evolution stage of the customization item")
    paint: Optional[List[UserDescendantCustomizingInnerPaintInner]] = Field(default=None, description="Paint information")
    __properties: ClassVar[List[str]] = ["customizing_item_slot_id", "customizing_item_type", "customizing_item_id", "customizing_item_evolution_stage", "customizing_item_current_evolution_stage", "paint"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserDescendantCustomizingInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in paint (list)
        _items = []
        if self.paint:
            for _item_paint in self.paint:
                if _item_paint:
                    _items.append(_item_paint.to_dict())
            _dict['paint'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserDescendantCustomizingInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "customizing_item_slot_id": obj.get("customizing_item_slot_id"),
            "customizing_item_type": obj.get("customizing_item_type"),
            "customizing_item_id": obj.get("customizing_item_id"),
            "customizing_item_evolution_stage": obj.get("customizing_item_evolution_stage"),
            "customizing_item_current_evolution_stage": obj.get("customizing_item_current_evolution_stage"),
            "paint": [UserDescendantCustomizingInnerPaintInner.from_dict(_item) for _item in obj["paint"]] if obj.get("paint") is not None else None
        })
        return _obj


