general:
  set-plural: 
    - meta
    - recommendation
paths:
  recommendation/module: module recomendations
  meta/research: research # no plural for research
schemas:
  skip:
    - User
    - Research