# coding: utf-8

# flake8: noqa

"""
    The First Descendant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "MetadataApi",
    "RecommendationApi",
    "UserApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AcquisitionDetailsInner",
    "AdaptLevelsInner",
    "AmorphousOpenConditionDescriptionsInner",
    "AmorphousRewardsInner",
    "AmorphousRewardsInnerOpenRewardInner",
    "AmorphousRewardsInnerOpenRewardInnerRewardItemInner",
    "ArcheTuningBoardGroupsInner",
    "ArcheTuningBoardsInner",
    "ArcheTuningBoardsInnerNodeInner",
    "ArcheTuningNodesInner",
    "ArcheTuningNodesInnerNodeEffectInner",
    "ConsumableMaterialsInner",
    "CoreSlotsInner",
    "CoreTypesInner",
    "CoreTypesInnerCoreOptionInner",
    "CoreTypesInnerCoreOptionInnerAvailableItemOptionInner",
    "CoreTypesInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect",
    "CoreTypesInnerCoreOptionInnerDetailInner",
    "CoreTypesInnerCoreOptionInnerDetailInnerRequiredCoreItem",
    "CustomizingItemsInner",
    "CustomizingItemsInnerCustomizingItemEvolutionStageInner",
    "DescendantGroupsInner",
    "DescendantLevelDetailsInner",
    "DescendantsInner",
    "DescendantsInnerDescendantSkillInner",
    "DescendantsInnerDescendantStatInner",
    "DescendantsInnerDescendantStatInnerStatDetailInner",
    "ErrorMessage",
    "ErrorMessageError",
    "ExternalComponentsInner",
    "ExternalComponentsInnerBaseStatInner",
    "ExternalComponentsInnerSetOptionDetailInner",
    "FellowLevelDetailsInner",
    "FellowsInner",
    "FellowsInnerFellowDetailInner",
    "FellowsInnerFellowDetailInnerStatEffectInner",
    "MasteryRankLevelDetailsInner",
    "MedalsInner",
    "MedalsInnerMedalDetailInner",
    "ModuleRecommendations",
    "ModuleRecommendationsDescendant",
    "ModuleRecommendationsDescendantRecommendationInner",
    "ModuleRecommendationsWeapon",
    "ModulesInner",
    "ModulesInnerModuleStatInner",
    "ReactorsInner",
    "ReactorsInnerReactorSkillPowerInner",
    "ReactorsInnerReactorSkillPowerInnerEnchantEffectInner",
    "ReactorsInnerReactorSkillPowerInnerSkillPowerCoefficientInner",
    "ResearchInner",
    "ResearchInnerResearchCostInner",
    "ResearchInnerResearchMaterialInner",
    "ResearchInnerResearchResultInner",
    "RewardsInner",
    "RewardsInnerBattleZoneInner",
    "RewardsInnerBattleZoneInnerRewardInner",
    "StatsInner",
    "TiersInner",
    "TitlesInner",
    "User",
    "UserArcheTuning",
    "UserArcheTuningArcheTuningInner",
    "UserArcheTuningArcheTuningInnerArcheTuningBoardInner",
    "UserArcheTuningArcheTuningInnerArcheTuningBoardInnerNodeInner",
    "UserBasic",
    "UserDescendant",
    "UserDescendantCustomizingInner",
    "UserDescendantCustomizingInnerPaintInner",
    "UserDescendantModuleInner",
    "UserExternalComponent",
    "UserExternalComponentExternalComponentInner",
    "UserExternalComponentExternalComponentInnerExternalComponentAdditionalStatInner",
    "UserReactor",
    "UserReactorReactorAdditionalStatInner",
    "UserWeapon",
    "UserWeaponWeaponInner",
    "UserWeaponWeaponInnerCoreInner",
    "UserWeaponWeaponInnerWeaponAdditionalStatInner",
    "VoidBattlesInner",
    "WeaponTypesInner",
    "WeaponsInner",
    "WeaponsInnerBaseStatInner",
    "WeaponsInnerFirearmAtkInner",
    "WeaponsInnerFirearmAtkInnerFirearmInner",
]

# import apis into sdk package
from tfd_api_client.api.metadata_api import MetadataApi as MetadataApi
from tfd_api_client.api.recommendation_api import RecommendationApi as RecommendationApi
from tfd_api_client.api.user_api import UserApi as UserApi

# import ApiClient
from tfd_api_client.api_response import ApiResponse as ApiResponse
from tfd_api_client.api_client import ApiClient as ApiClient
from tfd_api_client.configuration import Configuration as Configuration
from tfd_api_client.exceptions import OpenApiException as OpenApiException
from tfd_api_client.exceptions import ApiTypeError as ApiTypeError
from tfd_api_client.exceptions import ApiValueError as ApiValueError
from tfd_api_client.exceptions import ApiKeyError as ApiKeyError
from tfd_api_client.exceptions import ApiAttributeError as ApiAttributeError
from tfd_api_client.exceptions import ApiException as ApiException

# import models into sdk package
from tfd_api_client.models.acquisition_details_inner import AcquisitionDetailsInner as AcquisitionDetailsInner
from tfd_api_client.models.adapt_levels_inner import AdaptLevelsInner as AdaptLevelsInner
from tfd_api_client.models.amorphous_open_condition_descriptions_inner import AmorphousOpenConditionDescriptionsInner as AmorphousOpenConditionDescriptionsInner
from tfd_api_client.models.amorphous_rewards_inner import AmorphousRewardsInner as AmorphousRewardsInner
from tfd_api_client.models.amorphous_rewards_inner_open_reward_inner import AmorphousRewardsInnerOpenRewardInner as AmorphousRewardsInnerOpenRewardInner
from tfd_api_client.models.amorphous_rewards_inner_open_reward_inner_reward_item_inner import AmorphousRewardsInnerOpenRewardInnerRewardItemInner as AmorphousRewardsInnerOpenRewardInnerRewardItemInner
from tfd_api_client.models.arche_tuning_board_groups_inner import ArcheTuningBoardGroupsInner as ArcheTuningBoardGroupsInner
from tfd_api_client.models.arche_tuning_boards_inner import ArcheTuningBoardsInner as ArcheTuningBoardsInner
from tfd_api_client.models.arche_tuning_boards_inner_node_inner import ArcheTuningBoardsInnerNodeInner as ArcheTuningBoardsInnerNodeInner
from tfd_api_client.models.arche_tuning_nodes_inner import ArcheTuningNodesInner as ArcheTuningNodesInner
from tfd_api_client.models.arche_tuning_nodes_inner_node_effect_inner import ArcheTuningNodesInnerNodeEffectInner as ArcheTuningNodesInnerNodeEffectInner
from tfd_api_client.models.consumable_materials_inner import ConsumableMaterialsInner as ConsumableMaterialsInner
from tfd_api_client.models.core_slots_inner import CoreSlotsInner as CoreSlotsInner
from tfd_api_client.models.core_types_inner import CoreTypesInner as CoreTypesInner
from tfd_api_client.models.core_types_inner_core_option_inner import CoreTypesInnerCoreOptionInner as CoreTypesInnerCoreOptionInner
from tfd_api_client.models.core_types_inner_core_option_inner_available_item_option_inner import CoreTypesInnerCoreOptionInnerAvailableItemOptionInner as CoreTypesInnerCoreOptionInnerAvailableItemOptionInner
from tfd_api_client.models.core_types_inner_core_option_inner_available_item_option_inner_option_effect import CoreTypesInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect as CoreTypesInnerCoreOptionInnerAvailableItemOptionInnerOptionEffect
from tfd_api_client.models.core_types_inner_core_option_inner_detail_inner import CoreTypesInnerCoreOptionInnerDetailInner as CoreTypesInnerCoreOptionInnerDetailInner
from tfd_api_client.models.core_types_inner_core_option_inner_detail_inner_required_core_item import CoreTypesInnerCoreOptionInnerDetailInnerRequiredCoreItem as CoreTypesInnerCoreOptionInnerDetailInnerRequiredCoreItem
from tfd_api_client.models.customizing_items_inner import CustomizingItemsInner as CustomizingItemsInner
from tfd_api_client.models.customizing_items_inner_customizing_item_evolution_stage_inner import CustomizingItemsInnerCustomizingItemEvolutionStageInner as CustomizingItemsInnerCustomizingItemEvolutionStageInner
from tfd_api_client.models.descendant_groups_inner import DescendantGroupsInner as DescendantGroupsInner
from tfd_api_client.models.descendant_level_details_inner import DescendantLevelDetailsInner as DescendantLevelDetailsInner
from tfd_api_client.models.descendants_inner import DescendantsInner as DescendantsInner
from tfd_api_client.models.descendants_inner_descendant_skill_inner import DescendantsInnerDescendantSkillInner as DescendantsInnerDescendantSkillInner
from tfd_api_client.models.descendants_inner_descendant_stat_inner import DescendantsInnerDescendantStatInner as DescendantsInnerDescendantStatInner
from tfd_api_client.models.descendants_inner_descendant_stat_inner_stat_detail_inner import DescendantsInnerDescendantStatInnerStatDetailInner as DescendantsInnerDescendantStatInnerStatDetailInner
from tfd_api_client.models.error_message import ErrorMessage as ErrorMessage
from tfd_api_client.models.error_message_error import ErrorMessageError as ErrorMessageError
from tfd_api_client.models.external_components_inner import ExternalComponentsInner as ExternalComponentsInner
from tfd_api_client.models.external_components_inner_base_stat_inner import ExternalComponentsInnerBaseStatInner as ExternalComponentsInnerBaseStatInner
from tfd_api_client.models.external_components_inner_set_option_detail_inner import ExternalComponentsInnerSetOptionDetailInner as ExternalComponentsInnerSetOptionDetailInner
from tfd_api_client.models.fellow_level_details_inner import FellowLevelDetailsInner as FellowLevelDetailsInner
from tfd_api_client.models.fellows_inner import FellowsInner as FellowsInner
from tfd_api_client.models.fellows_inner_fellow_detail_inner import FellowsInnerFellowDetailInner as FellowsInnerFellowDetailInner
from tfd_api_client.models.fellows_inner_fellow_detail_inner_stat_effect_inner import FellowsInnerFellowDetailInnerStatEffectInner as FellowsInnerFellowDetailInnerStatEffectInner
from tfd_api_client.models.mastery_rank_level_details_inner import MasteryRankLevelDetailsInner as MasteryRankLevelDetailsInner
from tfd_api_client.models.medals_inner import MedalsInner as MedalsInner
from tfd_api_client.models.medals_inner_medal_detail_inner import MedalsInnerMedalDetailInner as MedalsInnerMedalDetailInner
from tfd_api_client.models.module_recommendations import ModuleRecommendations as ModuleRecommendations
from tfd_api_client.models.module_recommendations_descendant import ModuleRecommendationsDescendant as ModuleRecommendationsDescendant
from tfd_api_client.models.module_recommendations_descendant_recommendation_inner import ModuleRecommendationsDescendantRecommendationInner as ModuleRecommendationsDescendantRecommendationInner
from tfd_api_client.models.module_recommendations_weapon import ModuleRecommendationsWeapon as ModuleRecommendationsWeapon
from tfd_api_client.models.modules_inner import ModulesInner as ModulesInner
from tfd_api_client.models.modules_inner_module_stat_inner import ModulesInnerModuleStatInner as ModulesInnerModuleStatInner
from tfd_api_client.models.reactors_inner import ReactorsInner as ReactorsInner
from tfd_api_client.models.reactors_inner_reactor_skill_power_inner import ReactorsInnerReactorSkillPowerInner as ReactorsInnerReactorSkillPowerInner
from tfd_api_client.models.reactors_inner_reactor_skill_power_inner_enchant_effect_inner import ReactorsInnerReactorSkillPowerInnerEnchantEffectInner as ReactorsInnerReactorSkillPowerInnerEnchantEffectInner
from tfd_api_client.models.reactors_inner_reactor_skill_power_inner_skill_power_coefficient_inner import ReactorsInnerReactorSkillPowerInnerSkillPowerCoefficientInner as ReactorsInnerReactorSkillPowerInnerSkillPowerCoefficientInner
from tfd_api_client.models.research_inner import ResearchInner as ResearchInner
from tfd_api_client.models.research_inner_research_cost_inner import ResearchInnerResearchCostInner as ResearchInnerResearchCostInner
from tfd_api_client.models.research_inner_research_material_inner import ResearchInnerResearchMaterialInner as ResearchInnerResearchMaterialInner
from tfd_api_client.models.research_inner_research_result_inner import ResearchInnerResearchResultInner as ResearchInnerResearchResultInner
from tfd_api_client.models.rewards_inner import RewardsInner as RewardsInner
from tfd_api_client.models.rewards_inner_battle_zone_inner import RewardsInnerBattleZoneInner as RewardsInnerBattleZoneInner
from tfd_api_client.models.rewards_inner_battle_zone_inner_reward_inner import RewardsInnerBattleZoneInnerRewardInner as RewardsInnerBattleZoneInnerRewardInner
from tfd_api_client.models.stats_inner import StatsInner as StatsInner
from tfd_api_client.models.tiers_inner import TiersInner as TiersInner
from tfd_api_client.models.titles_inner import TitlesInner as TitlesInner
from tfd_api_client.models.user import User as User
from tfd_api_client.models.user_arche_tuning import UserArcheTuning as UserArcheTuning
from tfd_api_client.models.user_arche_tuning_arche_tuning_inner import UserArcheTuningArcheTuningInner as UserArcheTuningArcheTuningInner
from tfd_api_client.models.user_arche_tuning_arche_tuning_inner_arche_tuning_board_inner import UserArcheTuningArcheTuningInnerArcheTuningBoardInner as UserArcheTuningArcheTuningInnerArcheTuningBoardInner
from tfd_api_client.models.user_arche_tuning_arche_tuning_inner_arche_tuning_board_inner_node_inner import UserArcheTuningArcheTuningInnerArcheTuningBoardInnerNodeInner as UserArcheTuningArcheTuningInnerArcheTuningBoardInnerNodeInner
from tfd_api_client.models.user_basic import UserBasic as UserBasic
from tfd_api_client.models.user_descendant import UserDescendant as UserDescendant
from tfd_api_client.models.user_descendant_customizing_inner import UserDescendantCustomizingInner as UserDescendantCustomizingInner
from tfd_api_client.models.user_descendant_customizing_inner_paint_inner import UserDescendantCustomizingInnerPaintInner as UserDescendantCustomizingInnerPaintInner
from tfd_api_client.models.user_descendant_module_inner import UserDescendantModuleInner as UserDescendantModuleInner
from tfd_api_client.models.user_external_component import UserExternalComponent as UserExternalComponent
from tfd_api_client.models.user_external_component_external_component_inner import UserExternalComponentExternalComponentInner as UserExternalComponentExternalComponentInner
from tfd_api_client.models.user_external_component_external_component_inner_external_component_additional_stat_inner import UserExternalComponentExternalComponentInnerExternalComponentAdditionalStatInner as UserExternalComponentExternalComponentInnerExternalComponentAdditionalStatInner
from tfd_api_client.models.user_reactor import UserReactor as UserReactor
from tfd_api_client.models.user_reactor_reactor_additional_stat_inner import UserReactorReactorAdditionalStatInner as UserReactorReactorAdditionalStatInner
from tfd_api_client.models.user_weapon import UserWeapon as UserWeapon
from tfd_api_client.models.user_weapon_weapon_inner import UserWeaponWeaponInner as UserWeaponWeaponInner
from tfd_api_client.models.user_weapon_weapon_inner_core_inner import UserWeaponWeaponInnerCoreInner as UserWeaponWeaponInnerCoreInner
from tfd_api_client.models.user_weapon_weapon_inner_weapon_additional_stat_inner import UserWeaponWeaponInnerWeaponAdditionalStatInner as UserWeaponWeaponInnerWeaponAdditionalStatInner
from tfd_api_client.models.void_battles_inner import VoidBattlesInner as VoidBattlesInner
from tfd_api_client.models.weapon_types_inner import WeaponTypesInner as WeaponTypesInner
from tfd_api_client.models.weapons_inner import WeaponsInner as WeaponsInner
from tfd_api_client.models.weapons_inner_base_stat_inner import WeaponsInnerBaseStatInner as WeaponsInnerBaseStatInner
from tfd_api_client.models.weapons_inner_firearm_atk_inner import WeaponsInnerFirearmAtkInner as WeaponsInnerFirearmAtkInner
from tfd_api_client.models.weapons_inner_firearm_atk_inner_firearm_inner import WeaponsInnerFirearmAtkInnerFirearmInner as WeaponsInnerFirearmAtkInnerFirearmInner
